### ISSUE TITLE
Difference between ColonMapper and another work

### ISSUE THREAD

**Issue by haowang020110** [jmorlana/ColonMapper#2]
Hi, there
Congratulation! 
I noticed that your another work _Topological SLAM in colonoscopies leveraging deep features
and topological priors_ has been accpeted by MICCAI 2024.
I wonder the difference between the two work beacause the MICCAI's paper was not released.

**Comment by jmorlana** [comment]
Hi, thank you so much!
I will release the arxiv version this week, but a quick summary about the differences between ColonSLAM (MICCAI) and ColonMapper (ICRA) would be: 

1. ColonMapper performs mapping and localization in different stages, building a linear map in the mapping phase. ColonSLAM performs a topological SLAM, checking if the nodes inserted in the topological map have already been seen. In that case, nodes are merged. This allows to obtain richer maps and to identify revisits due to back and forth movements or potentially entry vs withdrawal place recognition.
2. Node building is done by a third-party 3D SLAM in ColonSLAM, while ColonMapper did an heuristic mapping with LoFTR. ColonSLAM takes the topological nodes obtained by the 3D SLAM and finds relationships between them.
3. A more powerful network is used

**Comment by haowang020110** [comment]
Thanks for your reply, looking forward to see the arxiv version!
